INSERT INTO genres (genre) VALUES ('alternative');
INSERT INTO genres (genre) VALUES ('alternative rock');
INSERT INTO genres (genre) VALUES ('grunge');
INSERT INTO genres (genre) VALUES ('indie rock');
INSERT INTO genres (genre) VALUES ('blues');
INSERT INTO genres (genre) VALUES ('classical');
INSERT INTO genres (genre) VALUES ('country');
INSERT INTO genres (genre) VALUES ('dubstep');
INSERT INTO genres (genre) VALUES ('garage');
INSERT INTO genres (genre) VALUES ('house');
INSERT INTO genres (genre) VALUES ('techno');
INSERT INTO genres (genre) VALUES ('swing');
INSERT INTO genres (genre) VALUES ('electro');
INSERT INTO genres (genre) VALUES ('electronic rock');
INSERT INTO genres (genre) VALUES ('enka');
INSERT INTO genres (genre) VALUES ('french pop');
INSERT INTO genres (genre) VALUES ('german folk');
INSERT INTO genres (genre) VALUES ('german pop');
INSERT INTO genres (genre) VALUES ('rap');
INSERT INTO genres (genre) VALUES ('hip-hop');
INSERT INTO genres (genre) VALUES ('indie pop');
INSERT INTO genres (genre) VALUES ('instrumental');
INSERT INTO genres (genre) VALUES ('jazz');
INSERT INTO genres (genre) VALUES ('big band');
INSERT INTO genres (genre) VALUES ('karaoke');
INSERT INTO genres (genre) VALUES ('latino');
INSERT INTO genres (genre) VALUES ('opera');
INSERT INTO genres (genre) VALUES ('pop');
INSERT INTO genres (genre) VALUES ('pop/rock');
INSERT INTO genres (genre) VALUES ('disco');
INSERT INTO genres (genre) VALUES ('soul');
INSERT INTO genres (genre) VALUES ('dancehall');
INSERT INTO genres (genre) VALUES ('dub');
INSERT INTO genres (genre) VALUES ('rock');
INSERT INTO genres (genre) VALUES ('blues rock');
INSERT INTO genres (genre) VALUES ('glam rock');
INSERT INTO genres (genre) VALUES ('hard rock');
INSERT INTO genres (genre) VALUES ('metal');
INSERT INTO genres (genre) VALUES ('musicals');
INSERT INTO genres (genre) VALUES ('soundtrack');
INSERT INTO genres (genre) VALUES ('spoken word');
INSERT INTO genres (genre) VALUES ('barbershop');
INSERT INTO genres (genre) VALUES ('africa');
INSERT INTO genres (genre) VALUES ('asia');
INSERT INTO genres (genre) VALUES ('caribbean');
INSERT INTO genres (genre) VALUES ('celtic');
INSERT INTO genres (genre) VALUES ('drinking songs');
INSERT INTO genres (genre) VALUES ('hawaii');
INSERT INTO genres (genre) VALUES ('indian pop');
INSERT INTO genres (genre) VALUES ('japanese pop');
INSERT INTO genres (genre) VALUES ('new wave');
