INSERT INTO skills (skill) VALUES ('drums');
INSERT INTO skills (skill) VALUES ('lyricist');
INSERT INTO skills (skill) VALUES ('guitar');
INSERT INTO skills (skill) VALUES ('vocals');
INSERT INTO skills (skill) VALUES ('piano');
INSERT INTO skills (skill) VALUES ('triangle');
INSERT INTO skills (skill) VALUES ('massive');
INSERT INTO skills (skill) VALUES ('sound engineer');
INSERT INTO skills (skill) VALUES ('reason');
INSERT INTO skills (skill) VALUES ('keyboard');
INSERT INTO skills (skill) VALUES ('trombone');
INSERT INTO skills (skill) VALUES ('album designer');
INSERT INTO skills (skill) VALUES ('bagpipes');
INSERT INTO skills (skill) VALUES ('banjo');
INSERT INTO skills (skill) VALUES ('bass drum');
INSERT INTO skills (skill) VALUES ('bassoon');
INSERT INTO skills (skill) VALUES ('bell');
INSERT INTO skills (skill) VALUES ('bongo');
INSERT INTO skills (skill) VALUES ('castanets');
INSERT INTO skills (skill) VALUES ('cello');
INSERT INTO skills (skill) VALUES ('clarinet');
INSERT INTO skills (skill) VALUES ('clavichord');
INSERT INTO skills (skill) VALUES ('conga drum');
INSERT INTO skills (skill) VALUES ('contrabassoon');
INSERT INTO skills (skill) VALUES ('cornet');
INSERT INTO skills (skill) VALUES ('cymbals');
INSERT INTO skills (skill) VALUES ('double bass');
INSERT INTO skills (skill) VALUES ('duclian');
INSERT INTO skills (skill) VALUES ('dynamophone');
INSERT INTO skills (skill) VALUES ('flute');
INSERT INTO skills (skill) VALUES ('flutophone');
INSERT INTO skills (skill) VALUES ('glockenspiel');
INSERT INTO skills (skill) VALUES ('gongs');
INSERT INTO skills (skill) VALUES ('guitar');
INSERT INTO skills (skill) VALUES ('harmonica');
INSERT INTO skills (skill) VALUES ('harp');
INSERT INTO skills (skill) VALUES ('harpsichord');
INSERT INTO skills (skill) VALUES ('lute');
INSERT INTO skills (skill) VALUES ('mandolin');
INSERT INTO skills (skill) VALUES ('maracas');
INSERT INTO skills (skill) VALUES ('mettallophone');
INSERT INTO skills (skill) VALUES ('musical box');
INSERT INTO skills (skill) VALUES ('oboe');
INSERT INTO skills (skill) VALUES ('recorder');
INSERT INTO skills (skill) VALUES ('saxophone');
INSERT INTO skills (skill) VALUES ('shawm');
INSERT INTO skills (skill) VALUES ('snare drum');
INSERT INTO skills (skill) VALUES ('steel drum');
INSERT INTO skills (skill) VALUES ('tambourine');
INSERT INTO skills (skill) VALUES ('theremin');
INSERT INTO skills (skill) VALUES ('trombone');
INSERT INTO skills (skill) VALUES ('trumpet');
INSERT INTO skills (skill) VALUES ('tuba');
INSERT INTO skills (skill) VALUES ('ukulele');
INSERT INTO skills (skill) VALUES ('viola');
INSERT INTO skills (skill) VALUES ('violin');
INSERT INTO skills (skill) VALUES ('xylophone');
INSERT INTO skills (skill) VALUES ('zither');
INSERT INTO skills (skill) VALUES ('fl studio');
INSERT INTO skills (skill) VALUES ('adobe audition');
INSERT INTO skills (skill) VALUES ('ardour');
INSERT INTO skills (skill) VALUES ('ableton live');
INSERT INTO skills (skill) VALUES ('tuxguitar');
INSERT INTO skills (skill) VALUES ('reaper');
INSERT INTO skills (skill) VALUES ('garageband');
INSERT INTO skills (skill) VALUES ('hydrogen');
INSERT INTO skills (skill) VALUES ('rosegarden');
INSERT INTO skills (skill) VALUES ('sony ascid pro');
INSERT INTO skills (skill) VALUES ('avid pro tools');
INSERT INTO skills (skill) VALUES ('logic pro');
INSERT INTO skills (skill) VALUES ('qtractor');
INSERT INTO skills (skill) VALUES ('linuxsampler');
INSERT INTO skills (skill) VALUES ('denemo');
INSERT INTO skills (skill) VALUES ('cubase');
INSERT INTO skills (skill) VALUES ('openmpt');
INSERT INTO skills (skill) VALUES ('audiotool');
INSERT INTO skills (skill) VALUES ('traverso daw');
INSERT INTO skills (skill) VALUES ('guitar rig');
INSERT INTO skills (skill) VALUES ('studio one');
INSERT INTO skills (skill) VALUES ('audiomulch');
INSERT INTO skills (skill) VALUES ('cakewalk sonar');
INSERT INTO skills (skill) VALUES ('ohm studio');
INSERT INTO skills (skill) VALUES ('synthfont');